### PR TITLE
Additional graduated symbols (UN-5385)

### PR DESCRIPTION
**Pull request by abstractalgo**
- [x] Natural Breaks (Jenks)
- [x] Pretty Breaks

**Testing**

- packaged plugin: [Unfolded-dev.zip](https://github.com/foursquare/qgis-plugin/files/11558116/Unfolded-dev.zip) (from commit `a91f85f`)
- follow similar instructions as in #64, just pick a different classification

**Notes**

See comments for some discussions on handling some of the differences between QGIS and Studio.

### CODE REVIEW

**Comment by heshan0131** [comment]
Isn't fixed interval the same as quantize?

**Comment by abstractalgo** [comment]
For all practical purposes - yes.

How classification works in QGIS, is that the user preselects the "Mode" (i.e. the scale), then parametrizes it, and then that generates classes (i.e. ranges).

So by using "Equal Interval", they specify the number of subranges, and that splits the global range of values into that number of subranges. Pseudo:
```py
value_range = [min_val..max_val]
subranges = value_range / number_of_ranges
```

And by using "Fixed Interval", they actually specify the size of the subrange and the total number of ranges, thus generating classes that may or may not cover the full range of values. Pseudo:
```py
for i in 0..number_of_ranges:
  subrange[i] = [i*subrange_size..(i+1)*subrange_size]
```

**Comment by ibgreen** [comment]
> Isn't fixed interval the same as quantize?

Given the users focus on getting the exact same result in Studio as in QGIS, I discussed with Dragan about whether we should just copy the color breaks if there is a risk that the two tools make different choices.

Perhaps for fixed/quantile there is not ambiguity, but we wondered if natural breaks clustering might be implemented differently on the two platform.

In the extreme, we could offer a plugin setting where the user chooses between actual color accuracy vs logical color scale preservation.

**Comment by ibgreen** [comment]
@heshan0131 Do we know what pretty breaks is? Seemed to be popular in the R notebook world based on quick googling.

**Comment by abstractalgo** [comment]
From what I've gathered, it's used because numbers at the edges of ranges can be truncated and that can look very nice on graphs because of that, because you don't have to account for many (or any) decimal places when making graphs.

It [seems](https://geoshen.com/posts/choropleth-maps#:~:text=The%20second) it's just Equal Intervals with rounded numbers.

**Comment by ibgreen** [comment]
Oh I see, the breaks are pretty in the sense that they are "numerically pretty".

**Comment by heshan0131** [comment]
> For all practical purposes - yes.
> 
> How classification works in QGIS, is that the user preselects the "Mode" (i.e. the scale), then parametrizes it, and then that generates classes (i.e. ranges).
> 
> So by using "Equal Interval", they specify the number of subranges, and that splits the global range of values into that number of subranges. Pseudo:
> 
> ```python
> value_range = [min_val..max_val]
> subranges = value_range / number_of_ranges
> ```
> 
> And by using "Fixed Interval", they actually specify the size of the subrange and the total number of ranges, thus generating classes that may or may not cover the full range of values. Pseudo:
> 
> ```python
> for i in 0..number_of_ranges:
>   subrange[i] = [i*subrange_size..(i+1)*subrange_size]
> ```

Ok i see, so in QGIS then can actually specify the min_val and max_val, then calculate the breaks. Unlike in studio we will automatically use the min max from the data domain. So even if the scale is the same, we might still show different colors because the domain are different

**Comment by abstractalgo** [comment]
> we might still show different colors because the domain are different

Yes, this can happen and lead to issues. As Ib mentioned in his [comment](https://github.com/foursquare/qgis-plugin/pull/71#issuecomment-1561826108), we may at some point expose this as an option toggle when doing export via plugin for users to pick if they want:
- exact values mapped to exact colors, probably then via Custom Breaks; or
- semantically same color scales in QGIS and Studio, i.e. same by name and intention, but that still may end up mapping to different values practically

I would leave this to users to report back on - if they don't have practical issues with the current approach (which slightly leans towards the first option atm), then it's not worth investing a lot of time doing all the changes around adjusting a lot of UI export dialog and branching in the code to handle different options.

**Pull request merged**
